# Generated by Django 5.2.3 on 2025-06-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=512000),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
