# Generated by Django 5.2.3 on 2025-06-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit', 'Time Limit Exceeded'), ('compilation_error', 'Compilation Error'), ('runtime_error', 'Runtime Error'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
